Feature/soma
Emanuelly03/calc-api-gqso-atv1 pull request #5
Opened 2021-08-18 02:14 UTC by Emanuelly03

se o parâmetro for uma letra o servidor retorna bad request

2021-09-07 21:24 UTC, laryssa15s requested changes
O código está bom. Entretanto, é importante fazer a alteração solicitada.

2021-09-07 21:24 UTC, laryssa15s commented on calc-api-924/src/main/java/app/Soma.java
> +           throw new BadRequestException(String.format("Contém parâmetro inválido"));
Informar qual parâmetro é inválido, para a devida atenção ao que deve ser digitado corretamente.

2021-09-14 22:28 UTC, Emanuelly03 commented on calc-api-924/src/main/java/app/Soma.java
> +           throw new BadRequestException(String.format("Contém parâmetro inválido"));
Correção realizada

2021-09-14 22:29 UTC, laryssa15s approved these changes

2021-09-14 22:30 UTC, merged